/** The ctx.okfDataplex service: key derivation, EntryGroup naming, staging, and the runner seam. */

import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { Context } from '@deepseek-ai/cordis'
import { parseConcept } from '@mindportalix/dsh-okf-core'
import OkfBundle from '@mindportalix/dsh-okf-bundle'
import OkfDataplex from '../src/index.ts'

/* oxlint-disable typescript/no-explicit-any -- assertions deep-inspect parsed YAML frontmatter of un-modeled shape. */

let root: string
let ctx: Context

async function mount(config: Record<string, unknown> = {}) {
  ctx = new Context()
  await ctx.plugin(OkfBundle, { root })
  await ctx.plugin(OkfDataplex, { project: 'acme', location: 'us-central1', entryGroupTemplate: 'okf_{tenant}', ...config })
}

beforeEach(async () => {
  root = await mkdtemp(join(tmpdir(), 'okf-dp-'))
})
afterEach(async () => {
  await rm(root, { recursive: true, force: true })
})

describe('keys and entry group', () => {
  it('derives the aspect and entry-type keys from project/location', async () => {
    await mount()
    expect(ctx.okfDataplex.okfAspectKey).toBe('acme.us-central1.okf')
    expect(ctx.okfDataplex.entryTypeKey).toBe('acme.us-central1.okf-bundle')
  })

  it('resolves the EntryGroup name with `local` when there is no tenant layer', async () => {
    await mount()
    expect(ctx.okfDataplex.entryGroup()).toBe('okf_local')
  })

  it('rejects an EntryGroup name that violates Dataplex naming rules', async () => {
    await mount({ entryGroupTemplate: 'BAD_NAME' })
    expect(() => ctx.okfDataplex.entryGroup()).toThrow(/does not match/)
  })
})

describe('stageBundle / unstage', () => {
  it('stages every concept and unstages back to clean OKF', async () => {
    await mount()
    await ctx.okf.writeConcept('metrics/revenue', {
      frontmatter: { type: 'Metric', title: 'Revenue', tags: ['finance'] },
      body: '# Definition\nx\n',
      actor: 'dsh/test',
    })
    const staged = await ctx.okfDataplex.stageBundle()
    // index.md and log.md are generated by writeConcept — they stage too.
    expect(staged['metrics/revenue.md']).toBeDefined()
    const stagedFm = parseConcept(staged['metrics/revenue.md']!).frontmatter as any
    expect(stagedFm.type).toBe('acme.us-central1.okf-bundle')
    expect(stagedFm.catalogEntry.aspects['acme.us-central1.okf'].okf_type).toBe('Metric')

    const back = ctx.okfDataplex.unstage(staged['metrics/revenue.md']!)
    expect((parseConcept(back).frontmatter as any).type).toBe('Metric')
  })
})

describe('push / pull without a runner', () => {
  it('push surfaces the "no runner" error (after staging succeeds)', async () => {
    await mount()
    await ctx.okf.writeConcept('m', { frontmatter: { type: 'Metric' }, body: 'x\n', actor: 'dsh/test' })
    await expect(ctx.okfDataplex.push(root)).rejects.toThrow(/no kcmd runner is configured/)
  })

  it('pull surfaces the "no runner" error', async () => {
    await mount()
    await expect(ctx.okfDataplex.pull(root)).rejects.toThrow(/no kcmd runner is configured/)
  })

  it('uses an injected runner when one is set', async () => {
    await mount()
    const calls: { args: readonly string[]; cwd: string }[] = []
    ctx.okfDataplex.setRunner({
      run: (args, cwd) => {
        calls.push({ args, cwd })
        return Promise.resolve('ok')
      },
    })
    await ctx.okf.writeConcept('m', { frontmatter: { type: 'Metric' }, body: 'x\n', actor: 'dsh/test' })
    expect(await ctx.okfDataplex.push('/staging')).toBe('ok')
    expect(await ctx.okfDataplex.pull('/staging')).toBe('ok')
    expect(calls).toEqual([
      { args: ['push'], cwd: '/staging' },
      { args: ['pull'], cwd: '/staging' },
    ])
  })
})
